import { Button } from "@heroui/button";
import { Card, CardBody } from "@heroui/card";
import { Link } from "@heroui/link";
import { Chip } from "@heroui/chip";
import { Divider } from "@heroui/divider";
import { Icon } from "@iconify/react";
import Image from "next/image";
import NextLink from "next/link";

import { LANGUAGES } from "@/config/languages";
import { siteConfig } from "@/config/site";

const FEATURES = [
  {
    icon: "solar:headphones-round-bold-duotone",
    title: "Audio Evaluation",
    description:
      "Listen to AI-generated speech samples and rate how natural they sound on a standardized MOS scale.",
    color: "text-primary",
    bg: "bg-primary/10",
  },
  {
    icon: "solar:chart-2-bold-duotone",
    title: "Real-time Analytics",
    description:
      "Track evaluation progress, MOS distributions, and inter-rater agreement with a powerful admin dashboard.",
    color: "text-success",
    bg: "bg-success/10",
  },
  {
    icon: "solar:shield-check-bold-duotone",
    title: "Anonymous & Secure",
    description:
      "All evaluations are fully anonymous. No accounts required. Data is stored securely and used only for research.",
    color: "text-warning",
    bg: "bg-warning/10",
  },
  {
    icon: "solar:smartphone-bold-duotone",
    title: "Mobile Optimized",
    description:
      "Evaluate from any device — phone, tablet, or desktop. Touch-friendly interface with optimized audio playback.",
    color: "text-secondary",
    bg: "bg-secondary/10",
  },
  {
    icon: "solar:global-bold-duotone",
    title: "Multi-Language",
    description:
      "Built for underrepresented African languages. Easily extensible to support new languages and dialects.",
    color: "text-primary",
    bg: "bg-primary/10",
  },
  {
    icon: "solar:code-bold-duotone",
    title: "Open Source",
    description:
      "Fully open source and community-driven. Inspect, modify, and contribute to the platform on GitHub.",
    color: "text-danger",
    bg: "bg-danger/10",
  },
];

const STEPS = [
  {
    step: "01",
    icon: "solar:headphones-round-bold-duotone",
    title: "Listen",
    description:
      "Put on headphones and listen to short audio clips generated by AI text-to-speech systems.",
  },
  {
    step: "02",
    icon: "solar:star-bold-duotone",
    title: "Rate",
    description:
      "Rate each clip on a scale of 1–5 based on how natural and human-like the speech sounds to you.",
  },
  {
    step: "03",
    icon: "solar:chart-bold-duotone",
    title: "Contribute",
    description:
      "Your anonymous ratings help researchers compare TTS models and improve voice tech for African languages.",
  },
];

const TESTIMONIALS = [
  {
    quote:
      "OpenMOS made it incredibly easy for us to collect MOS evaluations from native Luganda speakers. The data quality is excellent.",
    name: "Dr. Sarah Nakamya",
    role: "NLP Researcher, Makerere University",
    avatar: "solar:user-circle-bold-duotone",
  },
  {
    quote:
      "As a native Krio speaker, I loved how simple and accessible the evaluation process was. It took me less than 15 minutes.",
    name: "Mohamed Kamara",
    role: "Native Speaker Evaluator",
    avatar: "solar:user-circle-bold-duotone",
  },
  {
    quote:
      "The admin dashboard gives us all the analytics we need — MOS distributions, rater demographics, and model comparisons in one place.",
    name: "Prof. James Ochieng",
    role: "Speech Technology Lab Lead",
    avatar: "solar:user-circle-bold-duotone",
  },
];

const STATS = [
  { value: "31+", label: "Evaluations Completed" },
  { value: "All", label: "African Languages Supported" },
  { value: "~2 min", label: "Average Per Sample" },
  { value: "100%", label: "Open Source" },
];

export default function Home() {
  return (
    <>
      {/* ─── HERO SECTION ─── */}
      <section className="landing-section pb-0 lg:pb-0">
        <div className="max-w-[1280px] mx-auto">
          <div className="flex flex-col items-center text-center max-w-3xl mx-auto">
            <Chip
              className="mb-6 animate-fade-in-up"
              color="primary"
              size="sm"
              startContent={
                <Icon className="w-3.5 h-3.5 ml-1" icon="solar:star-bold" />
              }
              variant="flat"
            >
              Open Source Research Platform
            </Chip>

            <h1 className="text-4xl md:text-5xl lg:text-6xl font-extrabold tracking-tight text-foreground mb-6 animate-fade-in-up animate-delay-100">
              Evaluate AI Voice Quality{" "}
              <span className="text-primary">for African Languages</span>
            </h1>

            <p className="text-lg md:text-xl text-default-500 mb-8 max-w-2xl leading-relaxed animate-fade-in-up animate-delay-200">
              Help researchers improve text-to-speech technology by rating how
              natural AI-generated speech sounds. Anonymous, fast, and
              impactful.
            </p>

            <div className="flex flex-col sm:flex-row gap-3 mb-6 animate-fade-in-up animate-delay-300">
              <Button
                as={Link}
                className="font-semibold text-base h-12 px-8"
                color="primary"
                href="/start"
                size="lg"
                startContent={
                  <Icon
                    className="w-5 h-5"
                    icon="solar:play-circle-bold-duotone"
                  />
                }
              >
                Start Evaluation
              </Button>
              <Button
                as={Link}
                className="font-semibold text-base h-12 px-8"
                href="/admin"
                size="lg"
                startContent={
                  <Icon className="w-5 h-5" icon="solar:user-id-bold" />
                }
                variant="bordered"
              >
                Researcher Login
              </Button>
            </div>

            <div className="flex flex-wrap justify-center gap-x-6 gap-y-2 text-sm text-default-400 animate-fade-in-up animate-delay-400">
              <span className="flex items-center gap-1.5">
                <Icon
                  className="w-4 h-4 text-success"
                  icon="solar:check-circle-bold"
                />
                No account needed
              </span>
              <span className="flex items-center gap-1.5">
                <Icon
                  className="w-4 h-4 text-success"
                  icon="solar:check-circle-bold"
                />
                Takes 10–15 minutes
              </span>
              <span className="flex items-center gap-1.5">
                <Icon
                  className="w-4 h-4 text-success"
                  icon="solar:check-circle-bold"
                />
                Fully anonymous
              </span>
            </div>
          </div>

          {/* Hero Image */}
          <div className="mt-12 md:mt-16 animate-fade-in-up animate-delay-500">
            <div className="animate-float">
              <Image
                priority
                alt="OpenMOS Admin Dashboard showing MOS evaluation analytics"
                className="product-screenshot w-full"
                height={800}
                src="/open-mos.png"
                width={1400}
              />
            </div>
          </div>
        </div>
      </section>

      {/* ─── STATS BAR ─── */}
      <section className="py-12 md:py-16 border-y border-default-200 bg-default-50">
        <div className="max-w-[1280px] mx-auto px-4 md:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {STATS.map((stat) => (
              <div key={stat.label} className="text-center">
                <p className="text-3xl md:text-4xl font-extrabold text-foreground mb-1">
                  {stat.value}
                </p>
                <p className="text-sm text-default-500">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── HOW IT WORKS ─── */}
      <section className="landing-section" id="how-it-works">
        <div className="max-w-[1280px] mx-auto">
          <div className="text-center mb-12 md:mb-16">
            <h2 className="text-3xl md:text-4xl font-extrabold text-foreground mb-4">
              How It Works
            </h2>
            <p className="text-lg text-default-500 max-w-xl mx-auto">
              Three simple steps to contribute to groundbreaking research
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-12">
            {STEPS.map((item, index) => (
              <div key={item.step} className="relative text-center">
                {/* Connector line */}
                {index < STEPS.length - 1 && (
                  <div className="hidden md:block absolute top-10 left-[60%] w-[80%] h-px bg-default-200" />
                )}

                <div className="flex flex-col items-center">
                  <div className="relative mb-6">
                    <div className="w-20 h-20 rounded-2xl bg-primary/10 flex items-center justify-center">
                      <Icon className="w-9 h-9 text-primary" icon={item.icon} />
                    </div>
                    <span className="absolute -top-2 -right-2 w-7 h-7 rounded-full bg-primary text-white text-xs font-bold flex items-center justify-center">
                      {item.step}
                    </span>
                  </div>
                  <h3 className="text-xl font-bold text-foreground mb-2">
                    {item.title}
                  </h3>
                  <p className="text-default-500 leading-relaxed max-w-xs">
                    {item.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── FEATURES GRID ─── */}
      <section
        className="landing-section bg-default-50 border-y border-default-200"
        id="features"
      >
        <div className="max-w-[1280px] mx-auto">
          <div className="text-center mb-12 md:mb-16">
            <h2 className="text-3xl md:text-4xl font-extrabold text-foreground mb-4">
              Everything You Need
            </h2>
            <p className="text-lg text-default-500 max-w-xl mx-auto">
              A complete platform for collecting MOS evaluations at scale
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map((feature) => (
              <Card
                key={feature.title}
                className="landing-card border border-default-200"
                shadow="none"
              >
                <CardBody className="p-6">
                  <div
                    className={`w-12 h-12 rounded-xl ${feature.bg} flex items-center justify-center mb-4`}
                  >
                    <Icon
                      className={`w-6 h-6 ${feature.color}`}
                      icon={feature.icon}
                    />
                  </div>
                  <h3 className="text-lg font-bold text-foreground mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-default-500 text-sm leading-relaxed">
                    {feature.description}
                  </p>
                </CardBody>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ─── PRODUCT SHOWCASE ─── */}
      <section className="landing-section">
        <div className="max-w-[1280px] mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
            <div>
              <h2 className="text-3xl md:text-4xl font-extrabold text-foreground mb-6">
                Powerful Admin Dashboard
              </h2>
              <p className="text-lg text-default-500 mb-8 leading-relaxed">
                Manage your entire evaluation study from one clean interface.
                Upload audio, monitor progress, and export publication-ready
                data.
              </p>

              <ul className="space-y-4">
                {[
                  "Real-time MOS score distributions and analytics",
                  "Audio sample management with multi-model support",
                  "Rater demographics and completion tracking",
                  "One-click data export for academic papers",
                ].map((item) => (
                  <li
                    key={item}
                    className="flex items-start gap-3 text-default-600"
                  >
                    <Icon
                      className="w-5 h-5 text-success mt-0.5 shrink-0"
                      icon="solar:check-circle-bold"
                    />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>

              <Button
                as={Link}
                className="mt-8 font-semibold h-11"
                color="primary"
                href="/about"
                variant="flat"
              >
                Learn More
                <Icon
                  className="w-4 h-4 ml-1"
                  icon="solar:arrow-right-linear"
                />
              </Button>
            </div>

            <div>
              <Image
                alt="OpenMOS Dashboard with analytics and MOS comparison chart"
                className="product-screenshot w-full"
                height={800}
                src="/open-mos.png"
                width={1200}
              />
            </div>
          </div>
        </div>
      </section>

      {/* ─── SUPPORTED LANGUAGES ─── */}
      <section
        className="landing-section bg-default-50 border-y border-default-200"
        id="languages"
      >
        <div className="max-w-[1280px] mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-extrabold text-foreground mb-4">
              Supports All African Languages
            </h2>
            <p className="text-lg text-default-500 max-w-xl mx-auto">
              We&apos;re seeking native speakers to help evaluate AI speech
              quality across all underrepresented languages on the African
              continent
            </p>
          </div>

          <div className="flex flex-wrap justify-center gap-6 max-w-2xl mx-auto">
            {LANGUAGES.map((lang) => (
              <Card
                key={lang.code}
                className="landing-card border border-default-200 min-w-[200px]"
                shadow="none"
              >
                <CardBody className="flex flex-row items-center gap-4 p-5">
                  <span className="text-4xl">{lang.flag}</span>
                  <div>
                    <p className="font-bold text-foreground text-lg">
                      {lang.name}
                    </p>
                    <p className="text-sm text-default-500">{lang.region}</p>
                    {lang.speakers && (
                      <p className="text-xs text-primary font-medium mt-0.5">
                        {lang.speakers} speakers
                      </p>
                    )}
                  </div>
                </CardBody>
              </Card>
            ))}
          </div>

          <p className="text-center text-sm text-default-400 mt-8">
            More languages coming soon — contribute on{" "}
            <Link
              isExternal
              className="text-primary text-sm"
              href={siteConfig.links.github}
            >
              GitHub
            </Link>
          </p>
        </div>
      </section>

      {/* ─── TESTIMONIALS ─── */}
      <section className="landing-section" id="testimonials">
        <div className="max-w-[1280px] mx-auto">
          <div className="text-center mb-12 md:mb-16">
            <h2 className="text-3xl md:text-4xl font-extrabold text-foreground mb-4">
              Trusted by Researchers
            </h2>
            <p className="text-lg text-default-500 max-w-xl mx-auto">
              What researchers and evaluators are saying about OpenMOS
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {TESTIMONIALS.map((t) => (
              <Card
                key={t.name}
                className="landing-card border border-default-200"
                shadow="none"
              >
                <CardBody className="p-6">
                  <Icon
                    className="w-8 h-8 text-default-200 mb-4"
                    icon="solar:chat-square-like-bold-duotone"
                  />
                  <p className="text-default-600 leading-relaxed mb-6 text-sm">
                    &ldquo;{t.quote}&rdquo;
                  </p>
                  <Divider className="mb-4" />
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                      <Icon className="w-5 h-5 text-primary" icon={t.avatar} />
                    </div>
                    <div>
                      <p className="font-semibold text-foreground text-sm">
                        {t.name}
                      </p>
                      <p className="text-xs text-default-400">{t.role}</p>
                    </div>
                  </div>
                </CardBody>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ─── FINAL CTA ─── */}
      <section className="landing-section bg-primary" id="cta">
        <div className="max-w-[1280px] mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-extrabold text-white mb-4">
            Ready to Make an Impact?
          </h2>
          <p className="text-lg text-white/80 max-w-xl mx-auto mb-8">
            Your voice matters. Help us build better speech technology for
            millions of African language speakers.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button
              as={NextLink}
              className="font-semibold text-base h-12 px-8 bg-white text-primary"
              href="/start"
              size="lg"
              startContent={
                <Icon
                  className="w-5 h-5"
                  icon="solar:play-circle-bold-duotone"
                />
              }
            >
              Start Evaluation Now
            </Button>
            <Button
              as={NextLink}
              className="font-semibold text-base h-12 px-8 text-white border-white/30"
              href="/admin"
              size="lg"
              startContent={
                <Icon className="w-5 h-5" icon="solar:user-id-bold" />
              }
              variant="bordered"
            >
              Researcher Login
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}
